[workspace]
resolver = "3"
members = ["crates/baax", "crates/baax-cli"]

[workspace.package]
version = "3.0.0"
edition = "2024"
authors = ["Zinth"]

[workspace.dependencies]
baax = { path = "crates/baax" }

tokio = { version = "1.53", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

baad-utils = { git = "https://github.com/Deathemonic/BA-AD", version = "3.0.0" }
bacy = { git = "https://github.com/Deathemonic/BA-CY", version = "3.3.2" }
