[package]
name = "baax"
version = "0.1.0"
edition = "2024"

[lib]
name = "baax"
path = "src/lib.rs"

[[bin]]
name = "baax"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
baad = { git = "https://github.com/Deathemonic/BA-AD", version = "2.0.2" }
bacy = { git = "https://github.com/Deathemonic/BA-CY", version = "1.3.2" }
clap = "4.5.40"
tokio = { version = "1.45.1", features = ["full"] }
